<a href="https://colab.research.google.com/github/2403A51L03/2403A51L03_B51_P_DS/blob/main/Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1

In [7]:
import numpy as np
import matplotlib.pyplot as plt

In [8]:
A = np.random.randint(1, 11, size=(3, 3))
B = np.random.randint(1, 11, size=(3, 3))

In [9]:
addition_result = np.add(A, B)
subtraction_result = np.subtract(A, B)

In [10]:
print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nAddition (A + B):\n", addition_result)
print("\nSubtraction (A - B):\n", subtraction_result)

Matrix A:
 [[6 5 7]
 [1 3 7]
 [5 8 8]]

Matrix B:
 [[10  9  1]
 [ 3  2  3]
 [ 4  9  1]]

Addition (A + B):
 [[16 14  8]
 [ 4  5 10]
 [ 9 17  9]]

Subtraction (A - B):
 [[-4 -4  6]
 [-2  1  4]
 [ 1 -1  7]]


In [11]:
row, col = 1, 2
manual_add = A[row, col] + B[row, col]
manual_sub = A[row, col] - B[row, col]

In [12]:
print(f"\nManual Check at position (2,3):")
print(f"A[1,2] + B[1,2] = {A[row, col]} + {B[row, col]} = {manual_add}")
print(f"A[1,2] - B[1,2] = {A[row, col]} - {B[row, col]} = {manual_sub}")


Manual Check at position (2,3):
A[1,2] + B[1,2] = 7 + 3 = 10
A[1,2] - B[1,2] = 7 - 3 = 4


2

In [14]:
A = np.random.randint(1, 6, size=(3, 2))
B = np.random.randint(1, 6, size=(2, 3))

In [15]:
print("Matrix A (3x2):\n", A)
print("\nMatrix B (2x3):\n", B)

Matrix A (3x2):
 [[4 3]
 [5 3]
 [3 5]]

Matrix B (2x3):
 [[2 4 1]
 [4 1 2]]


In [16]:
C = np.dot(A, B)

In [17]:
print("\nResult of A dot B (3x3):\n", C)


Result of A dot B (3x3):
 [[20 19 10]
 [22 23 11]
 [26 17 13]]


In [18]:
row, col = 1, 2
manual_calc = A[row, 0]*B[0, col] + A[row, 1]*B[1, col]
print(f"\nManual check for C[2,3]: {manual_calc} (matches {C[row, col]})")


Manual check for C[2,3]: 11 (matches 11)
